name: Claude Data Interpretation

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-interpret:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude_interpret')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude_interpret')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude_interpret')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude_interpret') || contains(github.event.issue.title, '@claude_interpret')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # Required for Claude to comment on PRs
      issues: write         # Required for Claude to comment on issues
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Data Interpretation
        id: claude-interpret
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
          # Custom trigger phrase for data interpretation
          trigger_phrase: "@claude_interpret"
          
          # Custom instructions for data analysis interpretation
          custom_instructions: |
            You are a specialized data analysis interpreter. When responding to @claude_interpret requests:
            
            1. **Data Analysis Focus**: Prioritize interpretation of statistical results, metabolomics data, and scientific findings
            2. **Scientific Accuracy**: Ensure all interpretations are scientifically sound and properly contextualized
            3. **Visualization**: Suggest appropriate charts, graphs, or visualizations for the data
            4. **Statistical Interpretation**: Explain statistical significance, confidence intervals, and p-values in accessible terms
            5. **Biological Context**: For metabolomics data, provide biological pathway interpretations and functional insights
            6. **Reproducibility**: Emphasize reproducible analysis methods and proper documentation
            7. **Format**: Structure responses with clear sections: Summary, Key Findings, Statistical Analysis, Biological Implications, and Recommendations
            
            **IMPORTANT REPORTING REQUIREMENTS**:
            - ALWAYS create a detailed interpretation report file in the data directory
            - Save reports as: `reports/interpretation_YYYYMMDD_HHMMSS.md`
            - Include timestamp, analysis context, and full interpretation
            - Commit the report file to the repository
            - Provide both issue comment response AND file report
            
            Always ask clarifying questions if the data context is unclear and provide actionable insights for next steps.
          
          # Allow specific tools for data analysis and report generation
          allowed_tools: "Read,Write,Edit,MultiEdit,Glob,Grep,Bash(Rscript *),Bash(python *),Bash(jupyter *),Bash(mkdir *),Bash(git add *),Bash(git commit *)"
          
          # Environment variables for data analysis
          claude_env: |
            ANALYSIS_MODE: interpretation
            DATA_TYPE: metabolomics